# Generated by Django 5.0.2 on 2024-12-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bootstrap_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_mobile',
            field=models.CharField(max_length=15),
        ),
    ]
